# Generated by Django 3.1.5 on 2021-01-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columns', '0001_initial'),
        ('kanbans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanbans.kanban'),
        ),
    ]
