# Generated by Django 3.1.5 on 2021-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='background',
            field=models.PositiveIntegerField(choices=[(0, 'Default Background'), (1, 'Background 1'), (2, 'Background 2'), (3, 'Background 3'), (4, 'Background 4')], default=0),
        ),
    ]
