# Generated by Django 3.1.5 on 2021-01-29 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanbans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='kanbans_member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
