# Generated by Django 3.1.5 on 2021-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('deadline', models.DateTimeField(blank=True)),
                ('priority', models.PositiveIntegerField(blank=True, choices=[(1, '1 - High'), (2, '2 - Medium'), (3, '3 - Low')])),
            ],
        ),
    ]
