# Generated by Django 3.1.5 on 2021-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, '---------'), (1, '1 - High'), (2, '2 - Medium'), (3, '3 - Low')], default=0),
        ),
    ]
