# Generated by Django 3.1.5 on 2021-01-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='position',
            new_name='order',
        ),
    ]
