# Generated by Django 3.1.5 on 2021-01-27 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_auto_20210127_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='holders',
            field=models.ManyToManyField(blank=True, related_name='held_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
